# Generated by Django 3.2.4 on 2022-07-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_firstname', models.CharField(max_length=100)),
                ('member_lastname', models.CharField(max_length=100)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_phone', models.CharField(max_length=20)),
                ('member_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
