# Generated by Django 3.2.4 on 2022-07-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_phone',
            new_name='phone',
        ),
    ]
